### PR TITLE
Polish Text Collection

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
So exciting!! Thanks for the great work on this. Just a few little things.

> Reviewed 2 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-:-NkQvoKo8Ira3odMI3Su:bimuciq)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`package.json` line 81 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkQsVwzBMfUDUgWatQr:-NkQsVwzBMfUDUgWatQs:bfsnbre) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/da452301f179070721eb4e9101ce8dd5aa04e44d/package.json#L81)):*
> ```JSON
>     "@mui/icons-material": "^5.14.18",
>     "@mui/material": "^5.14.18",
>     "allotment": "^1.19.3"
> ```

I believe all of these should be devDependencies (`npm install -D <package_name>`). The main difference between the two is whether they are necessary to be present in the environment in production. Since all of these are bundled into the final webpack build and are not necessary to be available in the environment, these should be devDependencies, not dependencies.
___
*[`src/web-views/paratext-text-collection.web-view.scss` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkQt5TcDhGYMfCqJcuG:-NkQt5Td8usVnAUJCkrI:b-ex0070) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/4ec1fd83f2de0c0715557837fe21db113404b3e0/src/web-views/paratext-text-collection.web-view.scss#L57)):*
> ```SCSS
>       border-radius: 4px;
> 
>       transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms,
> ```

What is all this transition stuff doing? Do we need it, or can we remove it?
___
*[`src/web-views/components/verse-display.component.tsx` line 56 at r2](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkQuyplByl065cWhUJe:-NkQuyplByl065cWhUJf:b6n99dm) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/4ec1fd83f2de0c0715557837fe21db113404b3e0/src/web-views/components/verse-display.component.tsx#L56)):*
> ```XML
>     setAnchorEl(null);
>   };
>   const open = Boolean(anchorEl);
> ```

This should be `isOpen` to match our boolean naming conventions. Also note it is shorter to cast to boolean with `!!anchorEl`, but I don't know if it is particularly a JS community convention either way. I don't know of anywhere else in our code that uses `Boolean(...)`, but I don't think we have any standards around this.

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for all the help!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-:-NkQxtJUCcfygynMU-qN:bdda62x)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`package.json` line 81 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkQsVwzBMfUDUgWatQr:-NkQxWlO1WKDbNx4cvTC:b-ikwiso) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/da452301f179070721eb4e9101ce8dd5aa04e44d/package.json#L81)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe all of these should be devDependencies (`npm install -D <package_name>`). The main difference between the two is whether they are necessary to be present in the environment in production. Since all of these are bundled into the final webpack build and are not necessary to be available in the environment, these should be devDependencies, not dependencies.
</blockquote></details>

Done, moved them to dev deps
___
*[`src/web-views/paratext-text-collection.web-view.scss` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkQt5TcDhGYMfCqJcuG:-NkQwV5z5cGbjGxnsjw4:b-o9nh9f) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/4ec1fd83f2de0c0715557837fe21db113404b3e0/src/web-views/paratext-text-collection.web-view.scss#L57)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

What is all this transition stuff doing? Do we need it, or can we remove it?
</blockquote></details>

The div that this style applies to used to be a MUI Button. However, I moved its onClick event to it's  parent div, so that the entire verse box is clickable. Then it no longer made sense for the MUI Button to be there, so I changed it to be a div. But I wanted to keep the styling, so I copied the styling from MUI button.  No idea what things like `cubic-bezier` mean, but it looks good :joy: 
I'm guessing that some day we (or the UX team) will define some sort of global style set for titles like this, and than we can get rid of all this stuff
___
*[`src/web-views/components/verse-display.component.tsx` line 56 at r2](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkQuyplByl065cWhUJe:-NkQxf-L61euG1Fsu_4Q:b-896fix) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/4ec1fd83f2de0c0715557837fe21db113404b3e0/src/web-views/components/verse-display.component.tsx#L56)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This should be `isOpen` to match our boolean naming conventions. Also note it is shorter to cast to boolean with `!!anchorEl`, but I don't know if it is particularly a JS community convention either way. I don't know of anywhere else in our code that uses `Boolean(...)`, but I don't think we have any standards around this.
</blockquote></details>

Done.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
So close!! Looking forward to having a spiffy Text Collection extension :)



Side note: Oh there I am using "spiffy" on an object. Huh. :thinking: I guess sometimes spiffy does apply to objects.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-:-NkRTBSn0xSdVYBNwwt2:b-h47ytr)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/web-views/paratext-text-collection.web-view.scss` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkQt5TcDhGYMfCqJcuG:-NkRR6dz5V--PtDHszXz:blnmgtb) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/4ec1fd83f2de0c0715557837fe21db113404b3e0/src/web-views/paratext-text-collection.web-view.scss#L57)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

The div that this style applies to used to be a MUI Button. However, I moved its onClick event to it's  parent div, so that the entire verse box is clickable. Then it no longer made sense for the MUI Button to be there, so I changed it to be a div. But I wanted to keep the styling, so I copied the styling from MUI button.  No idea what things like `cubic-bezier` mean, but it looks good :joy: 
I'm guessing that some day we (or the UX team) will define some sort of global style set for titles like this, and than we can get rid of all this stuff
</blockquote></details>

Gotcha. `transition` basically automates interpolation between two values. So this is saying if you intend to change `background-color`, `box-shadow`, `border-color`, or `color`, it will interpolate the change between those over a period of time and with the specified interpolation function. I believe `cubic-bezier(...)` or various other functions like that are interpolation functions that make the transition interpolate differently than just linear.

All this to say I wonder if you will see any difference if you remove this transition line. If there is no difference, could you please remove it? Or maybe you want the `background-color` part to apply somewhere else like on `.verse-view`?
___
*[`src/web-views/components/verse-display.component.tsx` line 51 at r3](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkRRtrN3QxbLlZXkBgZ:-NkRRtrN3QxbLlZXkBg_:bf2eljd) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/002729a1e471b31be0a2e90dc0617f082f9e9c92/src/web-views/components/verse-display.component.tsx#L51)):*
> ```XML
> 
>   const handleClick = (event: MouseEvent<HTMLElement>) => {
>     setAnchorEl(event.currentTarget);
> ```

I think you might need to stop the event from bubbling up to above click handlers with `event.preventDefault()` here. Right now, clicking the `...` also opens or closes the chapter view.
___
*[`src/web-views/components/verse-display.component.tsx` line 63 at r3](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkRQr06DWuUsMsPhwug:-NkRQr06DWuUsMsPhwuh:b-xy0jkt) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/002729a1e471b31be0a2e90dc0617f082f9e9c92/src/web-views/components/verse-display.component.tsx#L63)):*
> ```XML
> 
>   return (
>     <div onClick={clickHandler} className={isSelected ? 'selected' : ''} aria-hidden="true">
> ```

Why did you move `cursor: pointer` from here? I could be missing something, but it seems this is interactable, not all of `.verse-view`. Not a big deal; no need unless you want to, but I'd recommend adding a class that sets the cursor to pointer on this div since right now the cursor is a pointer everywhere in the whole left pane, which is confusing since clicking outside the verses doesn't do anything.

**Review by rolfheij-sil — COMMENTED** [review]
Good stuff!

Spiffy still sounds like a dog name to me

https://rugrats.fandom.com/wiki/Spiffy

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-:-NkUd3CU9rRQnrTo2s0r:b-vwr4ym)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/web-views/paratext-text-collection.web-view.scss` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkQt5TcDhGYMfCqJcuG:-NkUUSvoEK3AW5390XIP:bcxeyvj) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/4ec1fd83f2de0c0715557837fe21db113404b3e0/src/web-views/paratext-text-collection.web-view.scss#L57)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Gotcha. `transition` basically automates interpolation between two values. So this is saying if you intend to change `background-color`, `box-shadow`, `border-color`, or `color`, it will interpolate the change between those over a period of time and with the specified interpolation function. I believe `cubic-bezier(...)` or various other functions like that are interpolation functions that make the transition interpolate differently than just linear.

All this to say I wonder if you will see any difference if you remove this transition line. If there is no difference, could you please remove it? Or maybe you want the `background-color` part to apply somewhere else like on `.verse-view`?
</blockquote></details>

Removing the transition doesn't make any difference. So it's gone now
___
*[`src/web-views/components/verse-display.component.tsx` line 51 at r3](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkRRtrN3QxbLlZXkBgZ:-NkUcflcAyHhpC_9qEch:b-fp4g08) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/002729a1e471b31be0a2e90dc0617f082f9e9c92/src/web-views/components/verse-display.component.tsx#L51)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think you might need to stop the event from bubbling up to above click handlers with `event.preventDefault()` here. Right now, clicking the `...` also opens or closes the chapter view.
</blockquote></details>

There was an issue with nested onClicks. Clicking the menu button would also trigger the onClick event of the entire verse div. So adding `event.stopPropagation();` in the nested onClicks helped resolve the issue
___
*[`src/web-views/components/verse-display.component.tsx` line 63 at r3](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkRQr06DWuUsMsPhwug:-NkUct0K4E_k-Sh5rxur:b-pz5yvq) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/002729a1e471b31be0a2e90dc0617f082f9e9c92/src/web-views/components/verse-display.component.tsx#L63)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why did you move `cursor: pointer` from here? I could be missing something, but it seems this is interactable, not all of `.verse-view`. Not a big deal; no need unless you want to, but I'd recommend adding a class that sets the cursor to pointer on this div since right now the cursor is a pointer everywhere in the whole left pane, which is confusing since clicking outside the verses doesn't do anything.
</blockquote></details>

Yeah you're right, I didn't think this through before. Now I did, and I made some more changes to the css

**Review by tjcouch-sil — APPROVED** [review]
Thanks for the adjustments! I am approving but took off auto-merge as I have some optional things I'd like you to consider. Feel free to merge in if you prefer not to make the changes I suggested.

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-:-NkVn2K32bHHM8QSyQ29:b-m0ta3l)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/web-views/paratext-text-collection.web-view.scss` line 46 at r5](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkVm9YkEI1LIzy82C-Y:-NkVm9YkEI1LIzy82C-Z:b-ao7zmd) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/12e265c206a30f907bae2b0f2e1de68f8dd28341/src/web-views/paratext-text-collection.web-view.scss#L46)):*
> ```SCSS
>     flex: 1;
> 
>     .verse#selected-verse {
> ```

To compound additional selectors onto a class, you can use the [parent selector `&`](https://sass-lang.com/documentation/style-rules/parent-selector/) instead of spelling out the whole selector :) I recommend this as a more concise and unified pattern. Optional though.

Like this:

```scss
.verse {
  &#selected-verse {
    <selected_stuff>
  }

  <other_stuff_just_verse>
}
```

This way, you have some stuff that applies to `.verse`, and some stuff that applies specifically to `.verse` with id `selected-verse`.

Note: I still recommend changing from using an `id` to using another class as mentioned below.
___
*[`src/web-views/components/verse-display.component.tsx` line 51 at r3](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkRRtrN3QxbLlZXkBgZ:-NkVhVyl3pKzjHgvwhuH:bijbs7h) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/002729a1e471b31be0a2e90dc0617f082f9e9c92/src/web-views/components/verse-display.component.tsx#L51)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

There was an issue with nested onClicks. Clicking the menu button would also trigger the onClick event of the entire verse div. So adding `event.stopPropagation();` in the nested onClicks helped resolve the issue
</blockquote></details>

Aaaah yes that's the one. Good call, sorry :) thanks!
___
*[`src/web-views/components/verse-display.component.tsx` line 63 at r3](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkRQr06DWuUsMsPhwug:-NkVjxs94lYEE6yWVk9-:b3fqjo5) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/002729a1e471b31be0a2e90dc0617f082f9e9c92/src/web-views/components/verse-display.component.tsx#L63)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Yeah you're right, I didn't think this through before. Now I did, and I made some more changes to the css
</blockquote></details>

Though I don't consider it worth blocking, I very strongly recommend against using `id` for small css changes like this. I suggest adding another class like you had before. You could do this like the following:

```typescript
className={`verse${isSelected ? ' selected' : ''}`}
```

Doing conditional classes like this is a common pattern :)

**Review by rolfheij-sil — COMMENTED** [review]
Thanks again. I did as you suggested

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-:-NkVsQOq0xKakVmn1XM6:b-xz3jzo)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/web-views/paratext-text-collection.web-view.scss` line 49 at r7](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkVuIA4EuHEDsrk1CnB:-NkVuIA4EuHEDsrk1CnC:b-v6bzj8) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/4a7f4dc847be261522a10bb0e00d0166a63749a2/src/web-views/paratext-text-collection.web-view.scss#L49)):*
> ```SCSS
>       cursor: pointer;
> 
>       .selected {
> ```

This needs to be `&.selected` in order for it to apply to the same element as the element in which it is nested. So this currently will resolve to this, which isn't causing the dark background to show up:

```css
.verse { ... }
.verse .selected { ... }
```

(note that there is a space between `.verse` and `.selected`, meaning it looks for an element with the `selected` class as a child of an element with the `verse` class)

We need the following:

```css
.verse { ... }
.verse.selected { ... }
```

`&` in scss accomplishes this goal :)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-:-NkVwU5pBE39--h95Vmq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/web-views/paratext-text-collection.web-view.scss` line 49 at r7](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/24#-NkVuIA4EuHEDsrk1CnB:-NkVwCKq-JTkg1DOufbW:bmj6zde) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/4a7f4dc847be261522a10bb0e00d0166a63749a2/src/web-views/paratext-text-collection.web-view.scss#L49)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Thanks! Learning a lot about CSS these days :sweat_smile: 
Sorry for mixing stuff related to tooltips into this review btw..
</blockquote></details>

It's all good. Stuff happens :)

Btw this `&` syntax (and anything nested) is `scss` stuff that transpiles down into native css classes :)

**Pull request merged**
