### PR TITLE
650 refactor imports (text collection)

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/28)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/28#-:-Nl3bwG84_bgnYKhm07e:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/28)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`.eslintrc.js` line 73 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/28#-Nl3c4k2-Rjpo2arAUSL:-Nl3c4k3ApbD4n8JS9WJ:by9tlf9) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/b2d26a372f0e4c3effe4593d72de6325f968e667/.eslintrc.js#L73)):*
> ```JavaScript
>     'no-null/no-null': 2,
>     'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
>     'no-restricted-imports': [
> ```

This will go into the template as well, right?

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/28)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

___
*[`.eslintrc.js` line 73 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/28#-Nl3c4k2-Rjpo2arAUSL:-Nl3uApO7M5b3e1ziCcu:b-k1fy1u) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/b2d26a372f0e4c3effe4593d72de6325f968e667/.eslintrc.js#L73)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This will go into the template as well, right?
</blockquote></details>

Yep. Still need to make PR's for the other extensions and templates

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/28#-:-Nl48kD_99gX0bbMwggG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
