### PR TITLE
1 start creating text collection

### LINKED ISSUE #1: Start Creating Text Collection with the USFM Data Provider
Create a view for text collection similar to the text collection in Paratext.

This can use mock data to simulate other projects/resources, but it does not need to use mock data and can reuse the same data from the USFM data provider

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Resolves #1 

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
Prettier has replaced spaces with tabs in a whole bunch of files. I don't know why. I will fix when I'm back.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-:-N_O8Sc05QcrGZRCLLRk:b-vtqtfo)* status: 0 of 14 files reviewed, 1 unresolved discussion

___
*[`lib/main.ts` line 53 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-N_O7uxc2e8l86E5_NU6:-N_O7uxc2e8l86E5_NU7:b-yw9vc2) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/main.ts#L53)):*
> ```XML
> 
> 	const unsubPromises = [
> 		papi.commands.registerCommand("test.echo", (message: string) => {
> ```

I know this is wrong, but I just needed to get the code to run without errors (my vacation was about to start :smile:). `"extension-template.do-stuff"`, that was there as part of the template resulted in an error, so I picked a random pre-existing command

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
This is exciting!! Thanks for the great work on this!

> Reviewed 1 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-:-Nai1nbgAVUx4a_f_uSw:b-rrs473)* status: 1 of 14 files reviewed, 6 unresolved discussions (waiting on @rolfheij-sil)

___
*[`lib/paratext-text-collection.web-view.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-Nahy5XW7VwQlnUwvpAW:-Nahy5XW7VwQlnUwvpAX:bopnhwx) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/paratext-text-collection.web-view.tsx#L18)):*
> ```XML
> 		verseNum: 1,
> 	});
> 	const [dummyData, setDummyData] =
> ```

Please name this what it represents like `[projectData, setProjectData]` so it is more legible. Also would recommend using the word "project" instead of "resource" as "project" encompasses readonly and editable projects/resources whereas "resource" is only readonly. I just learned this distinction recently; I was under the impression that they were talking about two different things before.
___
*[`lib/paratext-text-collection.web-view.tsx` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-Nahyhy34SiWliOiPNrx:-Nahyhy34SiWliOiPNry:b-ajgfal) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/paratext-text-collection.web-view.tsx#L51)):*
> ```XML
> 	);
> 
> 	useEffect(() => {
> ```

I recommend refactoring this `useEffect` and its corresponding `useState` into one `useMemo` since this is just creating a react-aware value that is a direct transformation of another react-aware value.
___
*[`lib/paratext-text-collection.web-view.tsx` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-Nahz0snBN0xaX2i3O4P:-Nahz0snBN0xaX2i3O4Q:b-ajgfal) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/paratext-text-collection.web-view.tsx#L66)):*
> ```XML
> 	}, [resourceText]);
> 
> 	useEffect(() => {
> ```

I recommend refactoring this `useEffect` and its corresponding `useState` into one `useMemo` since this is just creating a react-aware value that is a direct transformation of another react-aware value.
___
*[`lib/paratext-text-collection.web-view.tsx` line 143 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-NahzNvR5nxk3JF2ZCZ9:-NahzNvR5nxk3JF2ZCZA:bl3yznx) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/paratext-text-collection.web-view.tsx#L143)):*
> ```XML
> 		>
> 			<div
> 				style={{
> ```

I recommend changing these in-line styles into classes since [classes are generally recommended by the React devs](https://react.dev/reference/react-dom/components/common#applying-css-styles).
___
*[`lib/paratext-text-collection.web-view.tsx` line 192 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-NahzAbS6TnyhSXEFrJM:-NahzAbT2SUxIKP-ofyD:b6ltfi0) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/paratext-text-collection.web-view.tsx#L192)):*
> ```XML
> 			<div style={{ display: "flex" }}>
> 				{verseView}
> 				{showFullChapter && fullChapterView}
> ```

Since `fullChapterView` is conditionally rendered, I would recommend turning it into a function so it is not always evaluated and the JSX built into an object every render whether or not it is displayed.

**Review by rolfheij-sil — COMMENTED** [review]
Thanks! And thanks for your feedback!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-:-Nar9bsi1qVbQVbNl3UB:b524k9z)* status: 0 of 31 files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

___
*[`lib/paratext-text-collection.web-view.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-Nahy5XW7VwQlnUwvpAW:-Nar-NeVCbXULViVXlaJ:b-896fix) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/paratext-text-collection.web-view.tsx#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please name this what it represents like `[projectData, setProjectData]` so it is more legible. Also would recommend using the word "project" instead of "resource" as "project" encompasses readonly and editable projects/resources whereas "resource" is only readonly. I just learned this distinction recently; I was under the impression that they were talking about two different things before.
</blockquote></details>

Done.
___
*[`lib/paratext-text-collection.web-view.tsx` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-Nahyhy34SiWliOiPNrx:-Nar0eGeE9gZcCP5Vjnb:b-896fix) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/paratext-text-collection.web-view.tsx#L51)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I recommend refactoring this `useEffect` and its corresponding `useState` into one `useMemo` since this is just creating a react-aware value that is a direct transformation of another react-aware value.
</blockquote></details>

Done.
___
*[`lib/paratext-text-collection.web-view.tsx` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-Nahz0snBN0xaX2i3O4P:-Nar0eeF3noaSebeT8_Q:b-896fix) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/paratext-text-collection.web-view.tsx#L66)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I recommend refactoring this `useEffect` and its corresponding `useState` into one `useMemo` since this is just creating a react-aware value that is a direct transformation of another react-aware value.
</blockquote></details>

Done.
___
*[`lib/paratext-text-collection.web-view.tsx` line 143 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-NahzNvR5nxk3JF2ZCZ9:-Nar9ahT4ZF4e9cBl1fL:b-896fix) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/paratext-text-collection.web-view.tsx#L143)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I recommend changing these in-line styles into classes since [classes are generally recommended by the React devs](https://react.dev/reference/react-dom/components/common#applying-css-styles).
</blockquote></details>

Done.
___
*[`lib/paratext-text-collection.web-view.tsx` line 192 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-NahzAbS6TnyhSXEFrJM:-Nar0lyqCDQ-5oJ2TKnx:b-896fix) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/684bb79eaab892424430ae4cb8de26a4a2c9ebd9/lib/paratext-text-collection.web-view.tsx#L192)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since `fullChapterView` is conditionally rendered, I would recommend turning it into a function so it is not always evaluated and the JSX built into an object every render whether or not it is displayed.
</blockquote></details>

Done.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 4 of 14 files at r1, 30 of 30 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`public/package.json` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-NawCxvD1EuwX0eVUfVl:-NawCxvD1EuwX0eVUfVm:b-r0ctbu) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/76c52612d0437c19c475b79da7ed92b7124926c7/public/package.json#L1)):*
> ```JSON
> {
> ```

Please merge anything you want to keep from this file into the root `package.json` and delete this file. Sorry; forgot to mention this originally in the change notes.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`public/package.json` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-NawCxvD1EuwX0eVUfVl:-Nb-NhYW-CwK9O71hNiP:bsbew19) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/76c52612d0437c19c475b79da7ed92b7124926c7/public/package.json#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please merge anything you want to keep from this file into the root `package.json` and delete this file. Sorry; forgot to mention this originally in the change notes.
</blockquote></details>

Done. `manifest.json` is now the only file in `public`, is that right?

**Review by tjcouch-sil — APPROVED** [review]
Sorry for the wait! Looks great. Thanks for all the hard work!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-:-NbFjYZS2JZCFiYuOjcO:bn26cee)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`public/package.json` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-NawCxvD1EuwX0eVUfVl:-NbFjWYs-zqUU85vjdUB:b-989yli) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/76c52612d0437c19c475b79da7ed92b7124926c7/public/package.json#L1)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done. `manifest.json` is now the only file in `public`, is that right?
</blockquote></details>

Yep! Thanks!

**Review by rolfheij-sil — COMMENTED** [review]
The issue that found recently was caused by a typo in the .scss file. 
It said `display: 'flex';` instead of `display: flex;`

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-:-Nc9AgVb5YE910Og3kqS:by0s6kd)* status: 32 of 34 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for all the hard work on this!

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/2#-:-Nc9BNKvEbIUb_6-eP1n:b-ywiomv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
