### PR TITLE
Add tooltip

### PR DESCRIPTION
**Pull request by rolfheij-sil**
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/25)

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
Looks like you have branched it off from https://github.com/paranext/paranext-extension-text-collection/pull/24, so #.24 needs to go first, right?

**Comment by Sebastian-ubs** [comment]
also depends on https://github.com/paranext/paranext-core/pull/657/commits

**Comment by rolfheij-sil** [comment]
image
The first screenshot wasn't the best. The tooltip was still fading in or out. This is what it looks like when it's fully loaded.

Also yes, the other PR should go first, so I have not enabled auto merge for this PR

**Review by tjcouch-sil — APPROVED** [review]
Awesome! Thanks for this. Looks great.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/25#-:-NkVeegC5iIjzXV9ADnY:b-6jw7xu)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/web-views/paratext-text-collection.web-view.tsx` line 65 at r1](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/25#-NkVe-iE9ReRVHSqS_F4:-NkVe-iE9ReRVHSqS_F5:b8wv8xj) ([raw file](https://github.com/paranext/paranext-extension-text-collection/blob/aeb98076fe30d1ee2e6ae4bc653a3ed3b25748ef/src/web-views/paratext-text-collection.web-view.tsx#L65)):*
> ```XML
>     const newTitle = getTextCollectionTitle(projectsMetadata, verseRef);
>     const newTooltip = getTextCollectionTooltip(projectsMetadata);
>     if (newTitle)
> ```

Does this need to be `newTitle || newTooltip`? I don't know at the moment why this check is here, so I don't know. Just asking.

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/25)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
Oh I thought this was waiting on the other PR - oops

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-extension-text-collection/25#-:-NkVru3G6t2QqAEfkMjQ:b-1v5qow)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by rolfheij-sil** [comment]
Yes it should have been. That merge button just looked too good. rip. Let's get the other one merged asap :)

**Pull request merged**
